const mockListings = {
  mockListings: [
    {
      id: 1,
      seller_id: 123,
      title: "iPhone 12",
      description: "Good condition iPhone 12",
      price: 400,
      category: "Electronics",
      condition: "New",
      image_url: "https://iPhone12.jpg",
      available: true,
      tags: ["electronics"],
    },
    {
      id: 2,
      seller_id: 123,
      title: "Plant",
      description: "Lovely Plant",
      price: 0,
      category: "Decor",
      condition: "New",
      image_url: "https://plant.jpg",
      available: true,
      tags: ["plant", "green"],
    },
    {
      id: 2,
      seller_id: 123,
      title: "Royal King Bed",
      description: "Fits 5 LOL",
      price: 1000.22,
      category: "Furniture",
      condition: "New",
      image_url: "https://BigBed.jpg",
      available: true,
      tags: ["bed", "comdy", "A+ grade", "best sleep guaranteed"],
    },
    {
      id: 2,
      seller_id: 456,
      title: "Toothbrush",
      description: "yay teeth",
      price: 4.11,
      category: "Appliances",
      condition: "Like New",
      image_url: "https://toothbrush.jpg",
      available: true,
      tags: ["clean"],
    },
    {
      id: 2,
      seller_id: 456,
      title: "Jacket",
      description: "Racer jacket",
      price: 22.32,
      category: "Clothing & Accessories",
      condition: "Like New",
      image_url: "https://jacket.jpg",
      available: true,
      tags: [],
    },
    {
      id: 2,
      seller_id: 456,
      title: "Cs320",
      description: "signed by Tim Nelson",
      price: 15.00,
      category: "Books",
      condition: "Good",
      image_url: "https://cs320.jpg",
      available: true,
      tags: ["book"],
    },
    {
      id: 2,
      seller_id: 69,
      title: "Ratty",
      description: "Ratty event",
      price: 9.90,
      category: "Ticket & Event Passes",
      condition: "New",
      image_url: "https://ratty.jpg",
      available: true,
      tags: ["rats", "food", "ratty"],
    },
    {
      id: 2,
      seller_id: 90,
      title: "Fairy Lights",
      description: "multicolored lights that are shaped like mushrooms",
      price: 10,
      category: "Decor",
      condition: "Fair",
      image_url: "https://fairylightsmushroom.jpg",
      available: true,
      tags: ["lights", "multicolored", "mushrooms", "pretty"],
    },
    {
      id: 2,
      seller_id: 45,
      title: "Cat",
      description: "Cat plush",
      price: 4.35,
      category: "Other",
      condition: "Poor",
      image_url: "https://cat plush.jpg",
      available: true,
      tags: ["plush", "cat"],
    },
  ],
};

export default mockListings;
